"""Shared runtime contracts for SagaSmith system packages."""

from sagasmith_core.access import AccessDeniedError, AccessService, default_local_principal
from sagasmith_core.addons import AddonError, AddonService
from sagasmith_core.branches import BranchService
from sagasmith_core.campaigns import CampaignService
from sagasmith_core.characters import CharacterService
from sagasmith_core.continuity import ContinuityService
from sagasmith_core.continuity_commit import (
    FACT_KEY_WRITE_ACTIONS,
    ContinuityCommitService,
)
from sagasmith_core.database import Database
from sagasmith_core.documents import (
    DOCUMENT_NORMALIZER_VERSION,
    DOCUMENT_SOURCE_SUFFIXES,
    GENERIC_DOCUMENT_LAYOUT_PROFILE,
    CascadingOcrProvider,
    DocumentLayoutProfile,
    DocumentQualityError,
    NormalizedDocument,
    OcrPageLayout,
    OcrTextBlock,
    PageLocator,
    PdfDocumentConverter,
    PdfTextLayoutProvider,
    RapidOcrProvider,
    RenderedDocumentPage,
    apply_document_page_revisions,
    extract_pdf_page_text,
    file_sha256,
    normalize_document,
    normalized_document_page_text,
    ocr_layout_text,
    render_pdf_page,
)
from sagasmith_core.embeddings import (
    BgeEmbedder,
    BgeM3Embedder,
    BgeSmallEnEmbedder,
    BgeSmallZhEmbedder,
    EmbeddingProfile,
    configured_profiles,
    create_embedder,
)
from sagasmith_core.events import EventService
from sagasmith_core.idempotency import (
    IdempotencyConflictError,
    IdempotencyService,
    IdempotencyWrite,
    request_hash,
)
from sagasmith_core.import_jobs import ImportJobError, ImportJobService
from sagasmith_core.knowledge import ActorKnowledgeService
from sagasmith_core.memory import MemoryService, validate_subject_context_fact
from sagasmith_core.modules import (
    EXACT_MODULE_SOURCE_FIELD_ORDER,
    EXACT_MODULE_SOURCE_FIELDS,
    MANAGED_MODULE_SOURCE_FIELDS,
    ModuleService,
    clean_source_evidence_text,
    normalize_source_evidence_text,
)
from sagasmith_core.portable import (
    ACTOR_CARD_SCHEMA,
    ADDON_PACK_SCHEMA,
    ADDON_READINESS_SCHEMA_VERSION,
    MODULE_PACK_SCHEMA,
    MODULE_READINESS_SCHEMA_VERSION,
    PORTABLE_FORMAT,
    PORTABLE_SCHEMA_VERSION,
    PRESET_PACK_SCHEMA,
    RELEASE_MANIFEST_SCHEMA,
    RULE_PACK_SCHEMA,
    PortableContentError,
    build_actor_card,
    build_addon_pack,
    build_module_pack,
    build_portable_envelope,
    build_preset_pack,
    build_release_manifest,
    build_rule_pack,
    canonical_json,
    dumps_module_archive,
    dumps_portable,
    loads_module_archive,
    loads_portable,
    portable_checksum,
    portable_rule_chunk_key,
    portable_rule_definition_checksum,
    validate_actor_card,
    validate_addon_pack,
    validate_addon_readiness,
    validate_module_pack,
    validate_module_readiness,
    validate_portable_envelope,
    validate_portable_rule_source,
    validate_preset_pack,
    validate_release_manifest,
    validate_rule_pack,
)
from sagasmith_core.revisions import RevisionService
from sagasmith_core.rule_packs import RulePackService
from sagasmith_core.rule_profiles import RuleProfileService
from sagasmith_core.rule_receipts import RuleReceiptService
from sagasmith_core.rules import RuleService
from sagasmith_core.snapshots import SnapshotService
from sagasmith_core.state import (
    ActorKnowledgeTransfer,
    CharacterStateUpdate,
    StateMutationService,
)
from sagasmith_core.subject_context import SubjectContextService
from sagasmith_core.systems import SystemDefinition, SystemRegistry
from sagasmith_core.vector import VectorStore
from sagasmith_core.vector_jobs import VectorFlushResult, VectorIndexJobService

__all__ = [
    "ADDON_PACK_SCHEMA",
    "ADDON_READINESS_SCHEMA_VERSION",
    "DOCUMENT_NORMALIZER_VERSION",
    "DOCUMENT_SOURCE_SUFFIXES",
    "EXACT_MODULE_SOURCE_FIELD_ORDER",
    "EXACT_MODULE_SOURCE_FIELDS",
    "BgeEmbedder",
    "BgeM3Embedder",
    "BgeSmallEnEmbedder",
    "BgeSmallZhEmbedder",
    "ActorKnowledgeService",
    "AddonError",
    "AddonService",
    "ACTOR_CARD_SCHEMA",
    "AccessDeniedError",
    "AccessService",
    "BranchService",
    "CampaignService",
    "CascadingOcrProvider",
    "CharacterStateUpdate",
    "ActorKnowledgeTransfer",
    "CharacterService",
    "ContinuityService",
    "ContinuityCommitService",
    "Database",
    "DocumentQualityError",
    "DocumentLayoutProfile",
    "EmbeddingProfile",
    "EventService",
    "FACT_KEY_WRITE_ACTIONS",
    "GENERIC_DOCUMENT_LAYOUT_PROFILE",
    "MemoryService",
    "MANAGED_MODULE_SOURCE_FIELDS",
    "IdempotencyConflictError",
    "IdempotencyService",
    "IdempotencyWrite",
    "ImportJobError",
    "ImportJobService",
    "ModuleService",
    "MODULE_PACK_SCHEMA",
    "MODULE_READINESS_SCHEMA_VERSION",
    "NormalizedDocument",
    "OcrPageLayout",
    "OcrTextBlock",
    "PageLocator",
    "PdfDocumentConverter",
    "PdfTextLayoutProvider",
    "RapidOcrProvider",
    "PORTABLE_FORMAT",
    "PORTABLE_SCHEMA_VERSION",
    "PRESET_PACK_SCHEMA",
    "RELEASE_MANIFEST_SCHEMA",
    "RULE_PACK_SCHEMA",
    "PortableContentError",
    "RenderedDocumentPage",
    "apply_document_page_revisions",
    "RevisionService",
    "RuleProfileService",
    "RuleReceiptService",
    "RulePackService",
    "RuleService",
    "SnapshotService",
    "StateMutationService",
    "SubjectContextService",
    "SystemDefinition",
    "SystemRegistry",
    "VectorStore",
    "VectorFlushResult",
    "VectorIndexJobService",
    "configured_profiles",
    "build_actor_card",
    "build_addon_pack",
    "build_module_pack",
    "build_portable_envelope",
    "build_preset_pack",
    "build_release_manifest",
    "build_rule_pack",
    "canonical_json",
    "clean_source_evidence_text",
    "create_embedder",
    "default_local_principal",
    "dumps_portable",
    "dumps_module_archive",
    "extract_pdf_page_text",
    "file_sha256",
    "normalize_document",
    "normalized_document_page_text",
    "ocr_layout_text",
    "normalize_source_evidence_text",
    "loads_portable",
    "loads_module_archive",
    "portable_checksum",
    "portable_rule_chunk_key",
    "portable_rule_definition_checksum",
    "request_hash",
    "render_pdf_page",
    "validate_actor_card",
    "validate_addon_pack",
    "validate_addon_readiness",
    "validate_module_pack",
    "validate_module_readiness",
    "validate_portable_envelope",
    "validate_portable_rule_source",
    "validate_preset_pack",
    "validate_release_manifest",
    "validate_rule_pack",
    "validate_subject_context_fact",
]

__version__ = "0.2.0"
